version: "3"
services:

  vouch-proxy:
    image: voucher/vouch-proxy
    ports:
      - "9090:9090"
    networks:
      - static-content-network
    volumes:
      - "${PWD}/vouch-proxy/config:/config"
      - "${PWD}/vouch-proxy/data:/data"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  nginx:
    image: nginx
    ports:
      - "443:443"
    networks:
      - static-content-network
    volumes:
      - "${PWD}/web:/usr/share/nginx/html:ro"
      - "${PWD}/nginx/config/nginx.conf:/etc/nginx/nginx.conf:ro"
      - "${PWD}/nginx/certs:/etc/nginx/conf.d"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

networks:
  static-content-network:
