# vouch config
# bare minimum to get vouch running with OpenID Connect (such as okta)

vouch:
  # domains:
  # valid domains that the jwt cookies can be set into
  # the callback_urls will be to these domains
  #domains:
  #- yourdomain.com
  #- yourotherdomain.com

  # - OR -
  # instead of setting specific domains you may prefer to allow all users...
  # set allowAllUsers: true to use Vouch Proxy to just accept anyone who can authenticate at the configured provider
  allowAllUsers: true

oauth:
  # Generic OpenID Connect
  # including okta
  provider: oidc
  client_id:
  client_secret:
  auth_url: https://dev-257588.oktapreview.com/oauth2/default/v1/authorize
  token_url: https://dev-257588.oktapreview.com/oauth2/default/v1/token
  user_info_url: https://dev-257588.oktapreview.com/oauth2/default/v1/userinfo
  scopes:
    - openid
    - email
    - profile
  callback_url: http://localhost:9090/auth

